services:
  - type: worker
    name: Whittaker-Md -whatsapp-bot
    env: node
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: BOT_NAME
        value: Whittaker-md
